version: "3.9"
services:
  postgres_urlshortener:
    image: postgres:14.1-alpine
    container_name: postgres_urlshortener
    environment:
      POSTGRES_USER: shortdbuser
      POSTGRES_PASSWORD: shortdbpass
      POSTGRES_DB: urlshortenerdb
    ports:
      - "5433:5432"
    volumes:
      - postgresql_urlshortener_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgresql_urlshortener_data:
  grafana_data:
